// Presentation bindings for the approved studio prototype. Rendering stays in app.js.
const $=id=>document.getElementById(id),all=s=>[...document.querySelectorAll(s)];
function panel(name){document.querySelector('.desk').classList.toggle('show-export',name==='export');all('[data-panel-target]').forEach(b=>{const on=b.dataset.panelTarget===name;b.classList.toggle('active',on);b.setAttribute('aria-pressed',on);});if(name!=='export'){all('.inspector-panel').forEach(p=>p.hidden=p.dataset.panel!==name);$('materialSidebar').scrollTop=0;}}
all('[data-panel-target]').forEach(b=>b.addEventListener('click',()=>panel(b.dataset.panelTarget)));document.addEventListener('studio:panel',e=>panel(e.detail));panel('paint');
all('[data-animation]').forEach(b=>b.onclick=()=>{if($('animationStyle').disabled)return;$('animationStyle').value=b.dataset.animation;$('animationStyle').dispatchEvent(new Event('change'));syncMotion();});
all('[data-duration]').forEach(b=>b.onclick=()=>{if($('animationDuration').disabled)return;$('animationDuration').value=b.dataset.duration;$('animationDuration').dispatchEvent(new Event('change'));syncMotion();});
$('toggleRecordingMode').onclick=()=>{const mode=$('motionMode');if(mode.disabled)return;mode.value=mode.value==='manual'?'preset':'manual';mode.dispatchEvent(new Event('change'));syncMotion();};
function syncMotion(){const style=$('animationStyle').value,duration=$('animationDuration').value;all('[data-animation]').forEach(b=>{const on=b.dataset.animation===style;b.classList.toggle('selected',on);b.setAttribute('aria-pressed',on);b.disabled=$('animationStyle').disabled;b.querySelector('i').textContent=on?'●':'○';const recommended=$('animationStyle').dataset.recommended===b.dataset.animation;let mark=b.querySelector('small');if(!mark){mark=document.createElement('small');mark.textContent='推荐';b.querySelector('i').before(mark);}mark.hidden=!recommended;b.title=recommended?$('motionRecommendation').textContent:'';});all('[data-duration]').forEach(b=>{const on=b.dataset.duration===duration;b.classList.toggle('selected',on);b.setAttribute('aria-pressed',on);b.disabled=$('animationDuration').disabled;});$('durationSummary').textContent=duration+'s · 循环';$('playback').querySelectorAll('span')[1].textContent='00:0'+duration;$('toggleRecordingMode').textContent=$('motionMode').value==='manual'?'返回预设动画':'切换到手动录制';$('toggleRecordingMode').disabled=$('motionMode').disabled;}
document.addEventListener('studio:recording',syncMotion);document.addEventListener('studio:recording-ready',()=>{$('videoExportTab').click();syncMotion();});
all('.more-menu button').forEach(b=>b.addEventListener('click',()=>document.querySelector('.more-actions').open=false));document.addEventListener('click',e=>{const more=document.querySelector('.more-actions');if(!more.contains(e.target))more.open=false;});
let lastHistogram=0;document.addEventListener('studio:render',e=>{const {width,height,name}=e.detail;if(!$('animationStyle').dataset.recommended&&$('recommendMotion').onclick)$('recommendMotion').click();const preview=$('preview'),effect=$('effectPreview');if(effect.width!==preview.width||effect.height!==preview.height){effect.width=preview.width;effect.height=preview.height;}effect.getContext('2d').drawImage(preview,0,0);$('documentTitle').textContent=name;$('canvasDimensions').textContent=width+' × '+height;const scale=Math.min(1,1280/Math.max(width,height));$('videoDimensions').textContent=Math.round(width*scale/2)*2+' × '+Math.round(height*scale/2)*2;$('studioStatus').textContent=$('strokeCount').textContent+' · '+(document.querySelector('[data-paint-mode].selected')?.textContent.trim()||'融合');const preset=document.querySelector('.preset.selected');$('presetLabel').textContent=(preset?.textContent.trim()||'自定义')+'　⌄';if(performance.now()-lastHistogram<160)return;lastHistogram=performance.now();const histogram=$('histogram');histogram.width=240;histogram.height=85;const ctx=histogram.getContext('2d'),pixels=preview.getContext('2d').getImageData(0,0,preview.width,preview.height).data,bins=new Uint32Array(64);for(let i=0;i<pixels.length;i+=16)bins[Math.min(63,Math.floor((pixels[i]*.2126+pixels[i+1]*.7152+pixels[i+2]*.0722)/4))]++;const max=Math.max(...bins,1);ctx.fillStyle='#819676';ctx.beginPath();ctx.moveTo(0,85);bins.forEach((v,i)=>ctx.lineTo(i*240/63,85-v/max*72));ctx.lineTo(240,85);ctx.closePath();ctx.fill();});
syncMotion();
