import {test,expect} from '@playwright/test';
async function ready(page){const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await expect(page.locator('#loading')).toBeHidden();await page.waitForFunction(()=>!!document.querySelector('#startRecording').onclick);return errors;}
const pixels=page=>page.locator('#editor').evaluate(c=>c.toDataURL());
async function more(page,id){await page.locator('.more-actions summary').click();await page.click('#'+id);}

test('prototype panels drive real edits, comparison and image/preset export',async({page})=>{
 const errors=await ready(page);await page.click('[data-panel-target=glass]');await expect(page.locator('[data-glass=clear]')).toHaveClass(/selected/);await page.click('[data-glass=blue]');const tinted=await pixels(page);await page.click('[data-panel-target=effect]');await page.locator('#strokeThickness').focus();await page.keyboard.press('End');await page.waitForTimeout(120);expect(await pixels(page)).not.toBe(tinted);const edited=await pixels(page);const r=await page.locator('#comparePrevious').boundingBox();await page.mouse.move(r.x+r.width/2,r.y+r.height/2);await page.mouse.down();await page.waitForTimeout(100);expect(await pixels(page)).not.toBe(edited);await page.mouse.up();await page.waitForTimeout(100);expect(await pixels(page)).toBe(edited);
 await page.click('[data-panel-target=color]');await page.locator('#saturation').fill('40');await page.click('[data-panel-target=glass]');await more(page,'clear');await expect(page.locator('[data-glass=blue]')).toHaveClass(/selected/);await expect(page.locator('#glassTint')).toHaveValue('60');
 await page.click('#imageExportTab');const file=page.waitForEvent('download');await page.click('#export');expect((await file).suggestedFilename()).toMatch(/\.png$/);await page.click('#savePreset');await page.fill('#presetName','Studio regression');await page.click('#confirmSave');await expect(page.locator('.saved-card')).toHaveCount(1);await page.click('#closeLibrary');await more(page,'restoreAll');await page.click('#openLibrary');await page.getByRole('button',{name:'打开作品',exact:true}).click();await expect(page.locator('#presetDialog')).not.toBeVisible();await expect(page.locator('#glassTint')).toHaveValue('60');expect(errors).toEqual([]);
});

test('animation cards, real GIF download, preview and two-step manual recording',async({page})=>{
 const errors=await ready(page);await page.click('#videoExportTab');await page.click('[data-animation=vertical]');await expect(page.locator('#animationStyle')).toHaveValue('vertical');await page.click('[data-duration="4"]');const before=await pixels(page);await page.click('#previewAnimation');await expect(page.locator('#previewAnimation')).toHaveAttribute('aria-pressed','true');const frame=await page.locator('#videoPreview').evaluate(c=>c.toDataURL());await page.waitForTimeout(550);expect(await page.locator('#videoPreview').evaluate(c=>c.toDataURL())).not.toBe(frame);expect(await pixels(page)).toBe(before);await page.click('#previewAnimation');await page.selectOption('#motionFormat','gif');let download=page.waitForEvent('download');await page.click('#startRecording');expect((await download).suggestedFilename()).toMatch(/\.gif$/);await expect(page.locator('#recordingSection')).toHaveAttribute('data-state','done');
 await page.click('#toggleRecordingMode');await page.click('#startRecording');await expect(page.locator('#startRecording')).toHaveText('确认开始');await expect(page.locator('#recordingSection')).toHaveAttribute('data-state','idle');await page.click('#startRecording');await expect(page.locator('#recordingSection')).toHaveAttribute('data-state','recording');await page.waitForTimeout(350);download=page.waitForEvent('download');await page.click('#stopRecording');await download;expect(errors).toEqual([]);
});

test('mobile keeps canvas visible, batch images preserve edits and panel state',async({page})=>{
 const errors=await ready(page);await page.setViewportSize({width:390,height:844});await page.click('[data-panel-target=color]');await page.locator('#brightness').fill('15');const canvas=await page.locator('#editor').boundingBox();expect(canvas.y).toBeGreaterThan(0);expect(canvas.y+canvas.height).toBeLessThan(440);const sample=await page.request.get('/assets/sample.png');await page.locator('#fileInput').setInputFiles([{name:'a.png',mimeType:'image/png',buffer:await sample.body()},{name:'b.png',mimeType:'image/png',buffer:await sample.body()}]);await expect(page.locator('.image-tile')).toHaveCount(3);await page.locator('.image-tile').first().click();await expect(page.locator('#brightness')).toHaveValue('15');await page.click('[data-panel-target=export]');await expect(page.locator('.output')).toBeVisible();await page.click('#imageExportTab');await expect(page.locator('#export')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(390);expect(errors).toEqual([]);
});
